# This workflow is triggered on pull request events to the master branch, but ignores changes in the 'app' directory.

name: Build App

on:
    pull_request:
        branches: [ "master" ]
        paths-ignore:
            - 'api/**'
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            cache: 'npm'
            cache-dependency-path: 'app/package-lock.json'

        - name: Install dependencies
          run: npm ci
          working-directory: './app'

        - name: Check lint
          run: npm run format:check && npm run ts:check
          working-directory: './app'

        - name: Build
          run: npm run build
          working-directory: './app'


