# This workflow is triggered on push and pull request events to the master branch, but ignores changes in the 'app' directory.

name: Build API

on:
    push:
        branches: [ "master" ]
        paths-ignore:
            - 'app/**'
    pull_request:
        branches: [ "master" ]
        paths-ignore:
            - 'app/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            cache: 'npm'
            cache-dependency-path: 'api/package-lock.json'

        - name: Install dependencies
          run: npm ci
          working-directory: './api'

        - name: Check lint
          run: npm run format:check
          working-directory: './api'
