# This workflow is triggered on push event to the master branch, but ignores changes outside the 'app' directory.

name: Deploy App

on:
    push:
        branches: [ "master" ]
        paths-ignore:
            - 'api/**'
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
            cache: 'npm'
            cache-dependency-path: 'app/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: './app'

      - name: Build app
        run: |
          cd app
          npm run build

      - name: Copy env-config.js to dist/env-config.js
        run: |
          cp app/src/env/env-config.js app/dist/env-config.js

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: app/dist

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/index.html /env-config.js'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
