# This workflow is triggered on push event to the master branch, but ignores changes in the 'app' directory.

name: Deploy API

on:
    push:
        branches: [ "master" ]
        paths-ignore:
            - 'app/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - uses: appleboy/ssh-action@v1.2.2
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_KEY }}
                port: 22
                script: |
                    # move to repo directory
                    cd '~/chat-app'

                    # pull latest code from git
                    git checkout master
                    git pull origin master

                    # move to api directory
                    cd api

                    # install dependencies
                    npm ci

                    # restart the service
                    sudo systemctl restart chat-application